/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.Game
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class Game_Stub extends sapphire.appexamples.wordscramblewithfriends.app.Game implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public Game_Stub (java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.Integer $param_Integer_3) {
        super($param_String_1, $param_String_2, $param_Integer_3);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of setDictionary(HashMap)
    public void setDictionary(java.util.HashMap $param_HashMap_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setDictionary( $param_HashMap_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.Game.setDictionary(java.util.HashMap<java.lang.String, java.util.List<java.lang.String>>)";
                $__params.add($param_HashMap_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of quitGame(int)
    public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats quitGame(int $param_int_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.quitGame( $param_int_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats sapphire.appexamples.wordscramblewithfriends.app.Game.quitGame(int)";
                $__params.add($param_int_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats) $__result);
    }

    // Implementation of play(Integer, String)
    public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats play(java.lang.Integer $param_Integer_1, java.lang.String $param_String_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.play( $param_Integer_1,  $param_String_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats sapphire.appexamples.wordscramblewithfriends.app.Game.play(java.lang.Integer,java.lang.String)";
                $__params.add($param_Integer_1);
                $__params.add($param_String_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats) $__result);
    }

    // Implementation of pass(Integer)
    public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats pass(java.lang.Integer $param_Integer_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.pass( $param_Integer_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats sapphire.appexamples.wordscramblewithfriends.app.Game.pass(java.lang.Integer)";
                $__params.add($param_Integer_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats) $__result);
    }

    // Implementation of getSecondPlayerName()
    public java.lang.String getSecondPlayerName() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getSecondPlayerName();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String sapphire.appexamples.wordscramblewithfriends.app.Game.getSecondPlayerName()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of getScrambleLetters()
    public java.lang.String getScrambleLetters() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getScrambleLetters();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String sapphire.appexamples.wordscramblewithfriends.app.Game.getScrambleLetters()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of getRound()
    public int getRound() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getRound();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int sapphire.appexamples.wordscramblewithfriends.app.Game.getRound()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getPlayerTurn()
    public int getPlayerTurn() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getPlayerTurn();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int sapphire.appexamples.wordscramblewithfriends.app.Game.getPlayerTurn()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getLastRoundStats()
    public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats getLastRoundStats() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getLastRoundStats();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats sapphire.appexamples.wordscramblewithfriends.app.Game.getLastRoundStats()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.device.scramble.util.RoundStats) $__result);
    }

    // Implementation of getGameId()
    public int getGameId() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getGameId();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int sapphire.appexamples.wordscramblewithfriends.app.Game.getGameId()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getFirstPlayerName()
    public java.lang.String getFirstPlayerName() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getFirstPlayerName();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String sapphire.appexamples.wordscramblewithfriends.app.Game.getFirstPlayerName()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }
}
