/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.NotificationService
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class NotificationService_Stub extends sapphire.appexamples.wordscramblewithfriends.app.NotificationService implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public NotificationService_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of pollMessage()
    public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.ScrambleMessage pollMessage() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.pollMessage();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.device.scramble.util.ScrambleMessage sapphire.appexamples.wordscramblewithfriends.app.NotificationService.pollMessage()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.device.scramble.util.ScrambleMessage) $__result);
    }

    // Implementation of notify(ScrambleMessage)
    public void notify(sapphire.appexamples.wordscramblewithfriends.device.scramble.util.ScrambleMessage $param_ScrambleMessage_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.notify( $param_ScrambleMessage_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.NotificationService.notify(sapphire.appexamples.wordscramblewithfriends.device.scramble.util.ScrambleMessage)";
                $__params.add($param_ScrambleMessage_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of noMessages()
    public boolean noMessages() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.noMessages();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean sapphire.appexamples.wordscramblewithfriends.app.NotificationService.noMessages()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getNumMessages()
    public int getNumMessages() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNumMessages();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int sapphire.appexamples.wordscramblewithfriends.app.NotificationService.getNumMessages()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of clearMessages()
    public void clearMessages() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.clearMessages();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.NotificationService.clearMessages()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
