/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.ScrambleManager
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class ScrambleManager_Stub extends sapphire.appexamples.wordscramblewithfriends.app.ScrambleManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ScrambleManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of getUserManager()
    public sapphire.appexamples.wordscramblewithfriends.app.UserManager getUserManager() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUserManager();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.UserManager sapphire.appexamples.wordscramblewithfriends.app.ScrambleManager.getUserManager()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.UserManager) $__result);
    }

    // Implementation of getTableManager()
    public sapphire.appexamples.wordscramblewithfriends.app.TableManager getTableManager() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTableManager();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.TableManager sapphire.appexamples.wordscramblewithfriends.app.ScrambleManager.getTableManager()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.TableManager) $__result);
    }
}
