/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.TableManager
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class TableManager_Stub extends sapphire.appexamples.wordscramblewithfriends.app.TableManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public TableManager_Stub (sapphire.appexamples.wordscramblewithfriends.app.UserManager $param_UserManager_1) {
        super($param_UserManager_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of tableAvailable()
    public boolean tableAvailable() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.tableAvailable();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean sapphire.appexamples.wordscramblewithfriends.app.TableManager.tableAvailable()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of leaveTable(Table)
    public void leaveTable(sapphire.appexamples.wordscramblewithfriends.app.Table $param_Table_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.leaveTable( $param_Table_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.TableManager.leaveTable(sapphire.appexamples.wordscramblewithfriends.app.Table)";
                $__params.add($param_Table_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of joinTable(String, double, double)
    public sapphire.appexamples.wordscramblewithfriends.app.Table joinTable(java.lang.String $param_String_1, double $param_double_2, double $param_double_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.joinTable( $param_String_1,  $param_double_2,  $param_double_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.Table sapphire.appexamples.wordscramblewithfriends.app.TableManager.joinTable(java.lang.String,double,double)";
                $__params.add($param_String_1);
                $__params.add($param_double_2);
                $__params.add($param_double_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.Table) $__result);
    }

    // Implementation of hostTable(String, double, double)
    public sapphire.appexamples.wordscramblewithfriends.app.Table hostTable(java.lang.String $param_String_1, double $param_double_2, double $param_double_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.hostTable( $param_String_1,  $param_double_2,  $param_double_3);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.Table sapphire.appexamples.wordscramblewithfriends.app.TableManager.hostTable(java.lang.String,double,double)";
                $__params.add($param_String_1);
                $__params.add($param_double_2);
                $__params.add($param_double_3);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.Table) $__result);
    }
}
