/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.Table
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class Table_Stub extends sapphire.appexamples.wordscramblewithfriends.app.Table implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public Table_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of reset()
    public void reset() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.reset();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.Table.reset()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of joinTable(String)
    public boolean joinTable(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.joinTable( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean sapphire.appexamples.wordscramblewithfriends.app.Table.joinTable(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of isFull()
    public boolean isFull() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isFull();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean sapphire.appexamples.wordscramblewithfriends.app.Table.isFull()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of initialize(String, Integer)
    public void initialize(java.lang.String $param_String_1, java.lang.Integer $param_Integer_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.initialize( $param_String_1,  $param_Integer_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.Table.initialize(java.lang.String,java.lang.Integer)";
                $__params.add($param_String_1);
                $__params.add($param_Integer_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getTableId()
    public int getTableId() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTableId();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public int sapphire.appexamples.wordscramblewithfriends.app.Table.getTableId()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Integer) $__result).intValue();
    }

    // Implementation of getHostname()
    public java.lang.String getHostname() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getHostname();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String sapphire.appexamples.wordscramblewithfriends.app.Table.getHostname()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of getGuestname()
    public java.lang.String getGuestname() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getGuestname();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String sapphire.appexamples.wordscramblewithfriends.app.Table.getGuestname()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }
}
