/*
 * Stub for class sapphire.appexamples.wordscramblewithfriends.app.User
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.wordscramblewithfriends.app.stubs;


public final class User_Stub extends sapphire.appexamples.wordscramblewithfriends.app.User implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public User_Stub (sapphire.appexamples.wordscramblewithfriends.app.UserInfo $param_UserInfo_1) {
        super($param_UserInfo_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of setNotificationService(NotificationService)
    public void setNotificationService(sapphire.appexamples.wordscramblewithfriends.app.NotificationService $param_NotificationService_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setNotificationService( $param_NotificationService_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void sapphire.appexamples.wordscramblewithfriends.app.User.setNotificationService(sapphire.appexamples.wordscramblewithfriends.app.NotificationService)";
                $__params.add($param_NotificationService_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of isPlayingGame()
    public boolean isPlayingGame() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isPlayingGame();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean sapphire.appexamples.wordscramblewithfriends.app.User.isPlayingGame()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getUserInfo()
    public sapphire.appexamples.wordscramblewithfriends.app.UserInfo getUserInfo() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getUserInfo();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.UserInfo sapphire.appexamples.wordscramblewithfriends.app.User.getUserInfo()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.UserInfo) $__result);
    }

    // Implementation of getNotificationService()
    public sapphire.appexamples.wordscramblewithfriends.app.NotificationService getNotificationService() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getNotificationService();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.NotificationService sapphire.appexamples.wordscramblewithfriends.app.User.getNotificationService()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.NotificationService) $__result);
    }

    // Implementation of getGame()
    public sapphire.appexamples.wordscramblewithfriends.app.Game getGame() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getGame();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.wordscramblewithfriends.app.Game sapphire.appexamples.wordscramblewithfriends.app.User.getGame()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.wordscramblewithfriends.app.Game) $__result);
    }
}
