/*
 * RMI stub class
 * for class org.apache.harmony.rmi.server.DGCImpl
 * Compatible with stub protocol version 1.1
 *
 * Generated by DRL RMI Compiler (rmic).
 *
 * DO NOT EDIT!!!
 * Contents subject to change without notice!
 */
package org.apache.harmony.rmi.server;

import org.apache.harmony.rmi.internal.nls.Messages;

import harmony_java.rmi.MarshalException;
import harmony_java.rmi.RemoteException;
import harmony_java.rmi.UnexpectedException;
import harmony_java.rmi.UnmarshalException;
import harmony_java.rmi.dgc.DGC;
import harmony_java.rmi.dgc.Lease;
import harmony_java.rmi.dgc.VMID;
import harmony_java.rmi.server.ObjID;
import harmony_java.rmi.server.Operation;
import harmony_java.rmi.server.RemoteCall;
import harmony_java.rmi.server.RemoteObject;
import harmony_java.rmi.server.RemoteRef;
import harmony_java.rmi.server.RemoteStub;


public final class DGCImpl_Stub extends RemoteStub
        implements DGC {

    private static final long interfaceHash = -669196253586618813L;

    private static final Operation[] operations = {
        new Operation("void clean(ObjID[], long, VMID, boolean)"), //$NON-NLS-1$
        new Operation("Lease dirty(ObjID[], long, Lease)") //$NON-NLS-1$
    };

    public DGCImpl_Stub() {
        super();
    }

    public DGCImpl_Stub(RemoteRef ref) {
        super(ref);
    }

    // Implementation of clean(ObjID[], long, VMID, boolean)
    public void clean(ObjID[] $param_arrayOf_ObjID_1, long $param_long_2, VMID $param_VMID_3, boolean $param_boolean_4)
            throws RemoteException {
        try {
            RemoteCall call = ref.newCall((RemoteObject) this, operations, 0, interfaceHash);

            try {
                java.io.ObjectOutput out = call.getOutputStream();
                out.writeObject($param_arrayOf_ObjID_1);
                out.writeLong($param_long_2);
                out.writeObject($param_VMID_3);
                out.writeBoolean($param_boolean_4);
            } catch (java.io.IOException e) {
                throw new MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
            }

            ref.invoke(call);

            ref.done(call);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }

    // Implementation of dirty(ObjID[], long, Lease)
    public Lease dirty(ObjID[] $param_arrayOf_ObjID_1, long $param_long_2, Lease $param_Lease_3)
            throws RemoteException {
        try {
            RemoteCall call = ref.newCall((RemoteObject) this, operations, 1, interfaceHash);

            try {
                java.io.ObjectOutput out = call.getOutputStream();
                out.writeObject($param_arrayOf_ObjID_1);
                out.writeLong($param_long_2);
                out.writeObject($param_Lease_3);
            } catch (java.io.IOException e) {
                throw new MarshalException(Messages.getString("rmi.26"), e); //$NON-NLS-1$
            }

            ref.invoke(call);

            Lease $result;

            try {
                java.io.ObjectInput in = call.getInputStream();
                $result = (Lease) in.readObject();
            } catch (java.io.IOException e) {
                throw new UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
            } catch (java.lang.ClassNotFoundException e) {
                throw new UnmarshalException(Messages.getString("rmi.27"), e); //$NON-NLS-1$
            } finally {
                ref.done(call);
            }

            return $result;
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new UnexpectedException(Messages.getString("rmi.0C"), e); //$NON-NLS-1$
        }
    }
}
