/*
 * RMI skeleton class
 * for class org.apache.harmony.rmi.server.DGCImpl
 * Compatible with stub protocol version 1.1
 *
 * Generated by DRL RMI Compiler (rmic).
 *
 * DO NOT EDIT!!!
 * Contents subject to change without notice!
 */
package org.apache.harmony.rmi.server;

import org.apache.harmony.rmi.internal.nls.Messages;

import harmony_java.rmi.MarshalException;
import harmony_java.rmi.Remote;
import harmony_java.rmi.UnmarshalException;
import harmony_java.rmi.dgc.Lease;
import harmony_java.rmi.dgc.VMID;
import harmony_java.rmi.server.ObjID;
import harmony_java.rmi.server.Operation;
import harmony_java.rmi.server.RemoteCall;
import harmony_java.rmi.server.Skeleton;
import harmony_java.rmi.server.SkeletonMismatchException;


public final class DGCImpl_Skel implements Skeleton {

    private static final long interfaceHash = -669196253586618813L;

    private static final Operation[] operations = {
        new Operation("void clean(ObjID[], long, VMID, boolean)"), //$NON-NLS-1$
        new Operation("Lease dirty(ObjID[], long, Lease)") //$NON-NLS-1$
    };

    public Operation[] getOperations() {
        return (Operation[]) operations.clone();
    }

    public void dispatch(Remote obj, RemoteCall call, int opnum, long hash) throws java.lang.Exception {
        if (hash != interfaceHash) {
            // rmi.2D=Interface hash mismatch, expected: {0}, received: {1}
            throw new SkeletonMismatchException(
                    Messages.getString("rmi.2D", interfaceHash, hash)); //$NON-NLS-1$
        }

        org.apache.harmony.rmi.server.DGCImpl server = (org.apache.harmony.rmi.server.DGCImpl) obj;

        switch (opnum) {

        case 0: {    // clean(ObjID[], long, VMID, boolean)

            ObjID[] $param_arrayOf_ObjID_1;
            long $param_long_2;
            VMID $param_VMID_3;
            boolean $param_boolean_4;

            try {
                java.io.ObjectInput in = call.getInputStream();
                $param_arrayOf_ObjID_1 = (ObjID[]) in.readObject();
                $param_long_2 = in.readLong();
                $param_VMID_3 = (VMID) in.readObject();
                $param_boolean_4 = in.readBoolean();
            } catch (java.io.IOException e) {
                // rmi.2C=Error unmarshalling arguments
                throw new UnmarshalException(Messages.getString("rmi.2C"), e); //$NON-NLS-1$
            } catch (java.lang.ClassNotFoundException e) {
                // rmi.2C=Error unmarshalling arguments
                throw new UnmarshalException(Messages.getString("rmi.2C"), e); //$NON-NLS-1$
            } finally {
                call.releaseInputStream();
            }

            server.clean($param_arrayOf_ObjID_1, $param_long_2, $param_VMID_3, $param_boolean_4);

            try {
                call.getResultStream(true);
            } catch (java.io.IOException e) {
                // rmi.2A=Error marshalling return
                throw new MarshalException(Messages.getString("rmi.2A"), e); //$NON-NLS-1$
            }

            break;
        }

        case 1: {    // dirty(ObjID[], long, Lease)

            ObjID[] $param_arrayOf_ObjID_1;
            long $param_long_2;
            Lease $param_Lease_3;

            try {
                java.io.ObjectInput in = call.getInputStream();
                $param_arrayOf_ObjID_1 = (ObjID[]) in.readObject();
                $param_long_2 = in.readLong();
                $param_Lease_3 = (Lease) in.readObject();
            } catch (java.io.IOException e) {
                // rmi.2C=Error unmarshalling arguments
                throw new UnmarshalException(Messages.getString("rmi.2C"), e); //$NON-NLS-1$
            } catch (java.lang.ClassNotFoundException e) {
                // rmi.2C=Error unmarshalling arguments
                throw new UnmarshalException(Messages.getString("rmi.2C"), e); //$NON-NLS-1$
            } finally {
                call.releaseInputStream();
            }

            Lease $result = server.dirty($param_arrayOf_ObjID_1, $param_long_2, $param_Lease_3);

            try {
                java.io.ObjectOutput out = call.getResultStream(true);
                out.writeObject($result);
            } catch (java.io.IOException e) {
                // rmi.2A=Error marshalling return
                throw new MarshalException(Messages.getString("rmi.2A"), e); //$NON-NLS-1$
            }

            break;
        }

        default:
            // rmi.2B=Invalid method number: {0}
            throw new UnmarshalException(Messages.getString("rmi.2B", opnum)); //$NON-NLS-1$
        }
    }
}
